@startuml ユースケース図
actor 人事担当者 #DDDDDD;line:black;line.bold;
actor 社員 #DDDDDD;line:black;line.bold;

rectangle 従業員登録システム{
    usecase 社員情報を変更
    usecase 社員情報を登録
    usecase 社員情報を参照
    

}
社員.>社員情報を参照
    人事担当者.>社員情報を変更
    人事担当者.>社員情報を登録

@enduml
